---

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: network }
    - { role: packages }
    - { role: download }
    - { role: raspbian }
    - { role: kata-containers }

- hosts: master
#  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master }

- hosts: node
#  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node }
