---

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: network }
    - { role: download }
    - { role: raspbian }
    - { role: kata-containers }

- hosts: master
#  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master }

- hosts: node
#  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node }

- hosts: master
#  gather_facts: yes
  become: yes
  roles:
    - { role: rook-ceph }
  environment:
    K8S_AUTH_KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
  tags:
    - core
