---

- name: Copy K3s service file
  register: k3s_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check K3s service
  when: k3s_service.changed
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: Wait for node-token
  when: k3s_service.changed
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Register node-token file access mode
  when: k3s_service.changed
  stat:
    path: /var/lib/rancher/k3s/server
  register: p

- name: Change file access node-token
  when: k3s_service.changed
  file:
    path: /var/lib/rancher/k3s/server
    mode: "g+rx,o+rx"

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact: 
   token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- name: Restore node-token file access 
  when: k3s_service.changed
  file:
    path: /var/lib/rancher/k3s/server
    mode: "{{ p.stat.mode }}"

- name: Create directory .kube
  when: k3s_service.changed
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy config file to user home directory
  when: k3s_service.changed
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/{{ ansible_user }}/.kube/config
    remote_src: yes
    owner: "{{ ansible_user }}"

- name: Replace https://localhost:6443 by https://master-pi:6443
  when: k3s_service.changed
  replace:
    path: /home/{{ ansible_user }}/.kube/config
    regexp: 'https://localhost:6443'
    replace: 'https://{{master_ip}}:6443'

- name: Create kubectl symlink
  when: k3s_service.changed
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  when: k3s_service.changed
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create kubeconfig with remote hostname
  shell: "sed 's/localhost/{{ master }}/' /etc/rancher/k3s/k3s.yaml > /etc/rancher/k3s/k3s-remote.yaml"
  args:
    warn: false
  changed_when: false

- name: Copy kubectl config to ansible host
  fetch:
    src: /etc/rancher/k3s/k3s-remote.yaml
    flat: yes
    dest: "{{ lookup('env', 'HOME') }}/.kube/{{ cluster_name }}.yaml"

- name: Install extra packages on kube master
  apt:
    state: present
    name:
      - linux-modules-extra-{{ ansible_kernel }}
      - python3-pip
      - python3-virtualenv
    force_apt_get: "yes"

- name: Install openshift client on kube master
  pip:
    name: openshift
