---

- name: Verify k3s binary checksum
  stat:
    path: /usr/local/bin/k3s
    checksum_algorithm: sha256
  register: k3s_path

- name: Delete k3s if wrong version installed
  when: ( k3s_path.stat.get('checksum', None) != k3s_sha256 )
  file:
    path: /usr/local/bin/k3s
    state: absent

- name: Download k3s binary x64
  get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
#  when: ( ansible_facts.userspace_architecture == "x86_64" )
  when: ( ansible_facts.architecture == "x86_64" )
          and
        ( k3s_path.stat.get('checksum', None) != k3s_sha256 )

- name: Download k3s binary arm64
  get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-arm64
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when: ( ansible_facts.architecture is search("arm") )
          and
        ( ansible_facts.userspace_bits == "64" )
          and
        ( k3s_path.stat.get('checksum', None) != k3s_sha256 )

- name: Download k3s binary armhf
  get_url:
      url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-armhf
      dest: /usr/local/bin/k3s
      owner: root
      group: root
      mode: 755
  when: ( ansible_facts.architecture is search("arm") )
          and
        ( ansible_facts.userspace_bits == "32" )
          and
        ( k3s_path.stat.get('checksum', None) != k3s_sha256 )
