---

- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  register: k3s_service

- name: Enable and check K3s service
  when: k3s_service.changed
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
